### ISSUE TITLE
Generators so the whole dataset does not have to be in memory?

### ISSUE THREAD

**Issue by simPod** [shipmonk-rnd/doctrine-entity-preloader#10]
I'm heavily using `toIterable()`

However, `EntityPreloader::preload()` requires source entities as `list` so this cannot be done:

```php
        $preloader = new EntityPreloader($entityManager);

        $entities = $entityManager->createQueryBuilder()
            ->select('e')
            ->from(E::class, 'e')
            ...
            ->getQuery()
            ->toIterable();

        $preloader->preload($entities, 'relation');
```

Is there a chance `Generator` input is supported in the future?

**Comment by JanTvrdik** [comment]
How would you expect that to work? The preload needs to iterate over the `$entities` making the `toIterable()` pointless.

**Comment by simPod** [comment]
Hm, I see. Currently `toIterable()` with `addSelect()`s for 1:n relations
is more optimal in my case but I appreciate an attempt to tackle the orm
issue.
