### ISSUE TITLE
Doctrine 2 support?

### ISSUE THREAD

**Issue by shastik** [shipmonk-rnd/doctrine-entity-preloader#14]
Hi,

is there any chance to make it work with Doctrine 2?

I plan to move to Doctrine 3 as soon as possible but a lot of legacy projects are still using Doctrine 2 and an update to the newer version is not planned. I would like to start using this library also on legacy projects. 

Thank you

**Comment by janedbal** [comment]
Doctrine 2 is supported, [see composer.json](https://github.com/shipmonk-rnd/doctrine-entity-preloader/blob/c9485d5/composer.json).
